[package]
name = "space-domain"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[lib]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.4"
flatbuffers = "0.7"
space-macros = { version = "*", path = "../space-macros" }
commons = { version = "*", path = "../commons" }
specs = { version = "0.16.*", features = ["serde"] }
specs-derive = "0.4.0"
shred = { version = "0.10.*", default-features = false }
shred-derive = "0.6.*"
rayon-core="1.9.1"
