[package]
name = "space-domain"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[lib]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.7"
flatbuffers = "*"
space-macros = { version = "*", path = "../space-macros" }
specs = { version = "0.15.*", features = ["serde"] }
