[package]
name = "space-domain-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro=true

[dependencies]
quote = { version = "1.0.33", features = [] }
syn = { version = "2.0.39", features = [] }

[dev-dependencies]
log="0.4.*"
env_logger= "0.10.1"
