[package]
name = "space-flap"
version = "0.1.0"
edition = "2021"

[lib]
name = "space_flap"
crate-type = ["cdylib"]

[build-dependencies]
flapigen = { version = "0.6.0-pre8", path = "/home/sisso/work/_others/flapigen-rs/macroslib" }
env_logger = "0.7"
log = "0.4"
