[package]
name = "space-console"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[dependencies]
space-domain = { version = "*", path = "../space-domain" }
space-macros = { version = "*", path = "../space-macros" }
tui = "0.6.*"
termion = "*"
rand = "0.7"

