[package]
name = "space-console"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
space-domain = { version = "*", path = "../space-domain" }
tui = "0.6.*"
termion = "*"
rand = "0.7"
log="0.4.*"
env_logger="0.9.*"
