[package]
name = "rust-space"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[dependencies]

[lib]
name = "space_lib"
# crate-type = ["dylib"] # comment to run main
path = "src/lib.rs"

[[bin]]
name = "space-bin"
path = "src/bin.rs"
