[package]
name = "space-lib"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[lib]
name="ffi_space"
crate-type = ["cdylib"]

[dependencies]
libc = "*"
space-domain = { version = "*", path = "../space-domain" }
space-macros = { version = "*", path = "../space-macros" }
