[package]
name = "space-lib"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name="ffi_space"
crate-type = ["cdylib"]

[dependencies]
libc = "*"
space-domain = { version = "*", path = "../space-domain" }
commons = { version = "*", path = "../commons" }
