// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace space_data
{

public enum EntityKind : short
{
  Fleet = 0,
  Asteroid = 1,
  Station = 2,
};


}
