// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace space_data
{

using global::System;
using global::FlatBuffers;

public struct EntityDock : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public EntityDock __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public uint TargetId { get { return __p.bb.GetUint(__p.bb_pos + 4); } }

  public static Offset<space_data.EntityDock> CreateEntityDock(FlatBufferBuilder builder, uint Id, uint TargetId) {
    builder.Prep(4, 8);
    builder.PutUint(TargetId);
    builder.PutUint(Id);
    return new Offset<space_data.EntityDock>(builder.Offset);
  }
};


}
