// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace space_data
{

using global::System;
using global::FlatBuffers;

public struct Inputs : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static Inputs GetRootAsInputs(ByteBuffer _bb) { return GetRootAsInputs(_bb, new Inputs()); }
  public static Inputs GetRootAsInputs(ByteBuffer _bb, Inputs obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Inputs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool NewGame { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<space_data.Inputs> CreateInputs(FlatBufferBuilder builder,
      bool new_game = false) {
    builder.StartTable(1);
    Inputs.AddNewGame(builder, new_game);
    return Inputs.EndInputs(builder);
  }

  public static void StartInputs(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddNewGame(FlatBufferBuilder builder, bool newGame) { builder.AddBool(0, newGame, false); }
  public static Offset<space_data.Inputs> EndInputs(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<space_data.Inputs>(o);
  }
};


}
