[workspace]
members = [
  "commons",
  "space-domain",
#  "space-console",
  "space-2d-gui",
  "space-flap",
  "space-galaxy",
  "space-godot",
  "domain-b"
]

resolver="2"

#[profile.dev]
#opt-level = 3
#
#[profile.tests]
#opt-level = 3
