[workspace]
members = [
  "commons",
  "space-domain",
#  "space-lib",
#  "space-console",
#  "space-2d-gui",
  "space-flap",
#  "space-galaxy",
  "space-godot",
]

resolver="2"

#[profile.dev]
#opt-level = 3
#
#[profile.test]
#opt-level = 3
