[workspace]
members = [
  "commons",
#  "space-console",
#  "space-2d-gui",
  "space-galaxy",
  "space-godot",
  "space-domain",
  "space-domain-macros"
]

resolver="2"

#[profile.dev]
#opt-level = 3
#
#[profile.tests]
#opt-level = 3
