
// Generated by flapigen. Do not edit.

// This warning occurs, because both Rust and C# have mehtod `ToString()`.
#pragma warning disable CS0114

using System;
using System.Runtime.InteropServices;

namespace ffi_domain_2
{
    internal static class RustString {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void c_string_delete(IntPtr c_char_ptr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* *mut RustString */ IntPtr c_str_u16_to_string(/* *const u16 */ IntPtr c_string_ptr);

        internal static string rust_to_dotnet(/* *const u16 */ IntPtr c_string_ptr)
        {
            var dotnet_str = Marshal.PtrToStringUni(c_string_ptr);
            RustString.c_string_delete(c_string_ptr);
            return dotnet_str;
        }

        internal static /* *mut RustString */ IntPtr dotnet_to_rust(string dotnet_str)
        {
            var c_string_ptr = Marshal.StringToHGlobalUni(dotnet_str);
            var rust_string_ptr = c_str_u16_to_string(c_string_ptr);
            Marshal.FreeHGlobal(c_string_ptr);
            return rust_string_ptr;
        }
    }

    [System.Serializable]
    public class Error : System.Exception
    {
        public Error(string message) : base(message) { }
    }

    
    public enum ObjActionKind {
        Undock = 0,Jump = 1,Dock = 2,MoveTo = 3,MoveToTargetPos = 4,Extract = 5
    }
    
    public enum EventKind {
        Add = 0,Move = 1,Jump = 2,Dock = 3,Undock = 4
    }
    
    public class SectorData: IDisposable {
        internal IntPtr nativePtr;

        internal SectorData(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                SectorData_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void SectorData_delete(IntPtr __this);

        ~SectorData() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong SectorData_get_id(/* SectorData */ IntPtr __this);

        
        public  ulong GetId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = SectorData_get_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr SectorData_get_coords(/* SectorData */ IntPtr __this);

        
        public  Tuple<float, float> GetCoords() {
            var __this_0 = this.nativePtr;

            var __ret_0 = SectorData_get_coords(__this_0);
            var __ret_1 = RustTuple2Tfloatfloat.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* const c_str_u16 */ IntPtr SectorData_get_label(/* SectorData */ IntPtr __this);

        
        public  string GetLabel() {
            var __this_0 = this.nativePtr;

            var __ret_0 = SectorData_get_label(__this_0);
            var __ret_1 = RustString.rust_to_dotnet(__ret_0);
            return __ret_1;
        }
} // class

    
    public class JumpData: IDisposable {
        internal IntPtr nativePtr;

        internal JumpData(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                JumpData_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void JumpData_delete(IntPtr __this);

        ~JumpData() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong JumpData_get_id(/* JumpData */ IntPtr __this);

        
        public  ulong GetId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = JumpData_get_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr JumpData_get_coords(/* JumpData */ IntPtr __this);

        
        public  Tuple<float, float> GetCoords() {
            var __this_0 = this.nativePtr;

            var __ret_0 = JumpData_get_coords(__this_0);
            var __ret_1 = RustTuple2Tfloatfloat.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong JumpData_get_sector_id(/* JumpData */ IntPtr __this);

        
        public  ulong GetSectorId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = JumpData_get_sector_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong JumpData_get_to_sector_id(/* JumpData */ IntPtr __this);

        
        public  ulong GetToSectorId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = JumpData_get_to_sector_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr JumpData_get_to_coords(/* JumpData */ IntPtr __this);

        
        public  Tuple<float, float> GetToCoords() {
            var __this_0 = this.nativePtr;

            var __ret_0 = JumpData_get_to_coords(__this_0);
            var __ret_1 = RustTuple2Tfloatfloat.rust_to_dotnet(__ret_0);
            return __ret_1;
        }
} // class

    
    public class ObjOrbitData: IDisposable {
        internal IntPtr nativePtr;

        internal ObjOrbitData(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                ObjOrbitData_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void ObjOrbitData_delete(IntPtr __this);

        ~ObjOrbitData() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjOrbitData_get_parent_pos(/* ObjOrbitData */ IntPtr __this);

        
        public  Tuple<float, float> GetParentPos() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjOrbitData_get_parent_pos(__this_0);
            var __ret_1 = RustTuple2Tfloatfloat.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern float ObjOrbitData_get_radius(/* ObjOrbitData */ IntPtr __this);

        
        public  float GetRadius() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjOrbitData_get_radius(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }
} // class

    
    public class ObjCoords: IDisposable {
        internal IntPtr nativePtr;

        internal ObjCoords(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                ObjCoords_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void ObjCoords_delete(IntPtr __this);

        ~ObjCoords() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjCoords_get_coords(/* ObjCoords */ IntPtr __this);

        
        public  Tuple<float, float> GetCoords() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjCoords_get_coords(__this_0);
            var __ret_1 = RustTuple2Tfloatfloat.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong ObjCoords_get_sector_id(/* ObjCoords */ IntPtr __this);

        
        public  ulong GetSectorId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjCoords_get_sector_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjCoords_is_docked(/* ObjCoords */ IntPtr __this);

        
        public  bool IsDocked() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjCoords_is_docked(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }
} // class

    
    public class ObjData: IDisposable {
        internal IntPtr nativePtr;

        internal ObjData(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                ObjData_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void ObjData_delete(IntPtr __this);

        ~ObjData() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong ObjData_get_id(/* ObjData */ IntPtr __this);

        
        public  ulong GetId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_get_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong ObjData_get_sector_id(/* ObjData */ IntPtr __this);

        
        public  ulong GetSectorId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_get_sector_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjData_get_coords(/* ObjData */ IntPtr __this);

        
        public  Tuple<float, float> GetCoords() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_get_coords(__this_0);
            var __ret_1 = RustTuple2Tfloatfloat.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjData_get_docked_id(/* ObjData */ IntPtr __this);

        
        public  Option<ulong> GetDockedId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_get_docked_id(__this_0);
            var __ret_1 = RustOptionulong.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjData_get_orbit(/* ObjData */ IntPtr __this);

        
        public  Option<ObjOrbitData> GetOrbit() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_get_orbit(__this_0);
            var __ret_1 = RustOptionObjOrbitData.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjData_is_docked(/* ObjData */ IntPtr __this);

        
        public  bool IsDocked() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_is_docked(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjData_is_fleet(/* ObjData */ IntPtr __this);

        
        public  bool IsFleet() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_is_fleet(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjData_is_station(/* ObjData */ IntPtr __this);

        
        public  bool IsStation() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_is_station(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjData_is_asteroid(/* ObjData */ IntPtr __this);

        
        public  bool IsAsteroid() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_is_asteroid(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjData_is_jump(/* ObjData */ IntPtr __this);

        
        public  bool IsJump() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_is_jump(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjData_is_astro(/* ObjData */ IntPtr __this);

        
        public  bool IsAstro() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_is_astro(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjData_is_astro_star(/* ObjData */ IntPtr __this);

        
        public  bool IsAstroStar() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_is_astro_star(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjData_is_factory(/* ObjData */ IntPtr __this);

        
        public  bool IsFactory() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_is_factory(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjData_is_shipyard(/* ObjData */ IntPtr __this);

        
        public  bool IsShipyard() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjData_is_shipyard(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }
} // class

    
    public class ObjDesc: IDisposable {
        internal IntPtr nativePtr;

        internal ObjDesc(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                ObjDesc_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void ObjDesc_delete(IntPtr __this);

        ~ObjDesc() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong ObjDesc_get_id(/* ObjDesc */ IntPtr __this);

        
        public  ulong GetId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjDesc_get_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* const c_str_u16 */ IntPtr ObjDesc_get_label(/* ObjDesc */ IntPtr __this);

        
        public  string GetLabel() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjDesc_get_label(__this_0);
            var __ret_1 = RustString.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjDesc_get_action(/* ObjDesc */ IntPtr __this);

        
        public  Option<ObjAction> GetAction() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjDesc_get_action(__this_0);
            var __ret_1 = RustOptionObjAction.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjDesc_get_cargo(/* ObjDesc */ IntPtr __this);

        
        public  Option<ObjCargo> GetCargo() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjDesc_get_cargo(__this_0);
            var __ret_1 = RustOptionObjCargo.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjDesc_get_shipyard(/* ObjDesc */ IntPtr __this);

        
        public  Option<ObjShipyard> GetShipyard() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjDesc_get_shipyard(__this_0);
            var __ret_1 = RustOptionObjShipyard.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjDesc_get_factory(/* ObjDesc */ IntPtr __this);

        
        public  Option<ObjFactory> GetFactory() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjDesc_get_factory(__this_0);
            var __ret_1 = RustOptionObjFactory.rust_to_dotnet(__ret_0);
            return __ret_1;
        }
} // class

    
    public class ObjAction: IDisposable {
        internal IntPtr nativePtr;

        internal ObjAction(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                ObjAction_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void ObjAction_delete(IntPtr __this);

        ~ObjAction() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern uint ObjAction_get_kind(/* ObjAction */ IntPtr __this);

        
        public  ObjActionKind GetKind() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjAction_get_kind(__this_0);
            var __ret_1 = (ObjActionKind)__ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjAction_get_target(/* ObjAction */ IntPtr __this);

        
        public  Option<ulong> GetTarget() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjAction_get_target(__this_0);
            var __ret_1 = RustOptionulong.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjAction_get_pos(/* ObjAction */ IntPtr __this);

        
        public  Option<Tuple<float, float>> GetPos() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjAction_get_pos(__this_0);
            var __ret_1 = RustOptionTuple60float4432float62.rust_to_dotnet(__ret_0);
            return __ret_1;
        }
} // class

    
    public class ObjCargo: IDisposable {
        internal IntPtr nativePtr;

        internal ObjCargo(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                ObjCargo_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void ObjCargo_delete(IntPtr __this);

        ~ObjCargo() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern uint ObjCargo_volume_total(/* ObjCargo */ IntPtr __this);

        
        public  uint VolumeTotal() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjCargo_volume_total(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern uint ObjCargo_volume_max(/* ObjCargo */ IntPtr __this);

        
        public  uint VolumeMax() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjCargo_volume_max(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr ObjCargo_get_wares(/* ObjCargo */ IntPtr __this);

        
        public  System.Collections.Generic.List<Tuple<ulong, uint>> GetWares() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjCargo_get_wares(__this_0);
            var __ret_1 = RustVecTuple60ulong4432uint62.rust_to_dotnet(__ret_0);
            return __ret_1;
        }
} // class

    
    public class EventData: IDisposable {
        internal IntPtr nativePtr;

        internal EventData(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                EventData_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void EventData_delete(IntPtr __this);

        ~EventData() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern uint EventData_get_kind(/* EventData */ IntPtr __this);

        
        public  EventKind GetKind() {
            var __this_0 = this.nativePtr;

            var __ret_0 = EventData_get_kind(__this_0);
            var __ret_1 = (EventKind)__ret_0;
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong EventData_get_id(/* EventData */ IntPtr __this);

        
        public  ulong GetId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = EventData_get_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }
} // class

    
    public class WareData: IDisposable {
        internal IntPtr nativePtr;

        internal WareData(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                WareData_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void WareData_delete(IntPtr __this);

        ~WareData() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* const c_str_u16 */ IntPtr WareData_get_label(/* WareData */ IntPtr __this);

        
        public  string GetLabel() {
            var __this_0 = this.nativePtr;

            var __ret_0 = WareData_get_label(__this_0);
            var __ret_1 = RustString.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong WareData_get_id(/* WareData */ IntPtr __this);

        
        public  ulong GetId() {
            var __this_0 = this.nativePtr;

            var __ret_0 = WareData_get_id(__this_0);
            var __ret_1 = __ret_0;
            return __ret_1;
        }
} // class

    
    public class SpaceGame: IDisposable {
        internal IntPtr nativePtr;

        internal SpaceGame(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                SpaceGame_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void SpaceGame_delete(IntPtr __this);

        ~SpaceGame() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* SpaceGame */ IntPtr SpaceGame_new(/* Option */ IntPtr rgs);

        
        public  SpaceGame (System.Collections.Generic.List<string> rgs_0) {
            var rgs_1 = RustVecstring.dotnet_to_rust(rgs_0);
            this.nativePtr = SpaceGame_new(rgs_1);
            
            
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr SpaceGame_get_sectors(/* SpaceGame */ IntPtr __this);

        
        public  System.Collections.Generic.List<SectorData> GetSectors() {
            var __this_0 = this.nativePtr;

            var __ret_0 = SpaceGame_get_sectors(__this_0);
            var __ret_1 = RustVecSectorData.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr SpaceGame_list_jumps(/* SpaceGame */ IntPtr __this);

        
        public  System.Collections.Generic.List<JumpData> ListJumps() {
            var __this_0 = this.nativePtr;

            var __ret_0 = SpaceGame_list_jumps(__this_0);
            var __ret_1 = RustVecJumpData.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr SpaceGame_get_jump(/* SpaceGame */ IntPtr __this, ulong id);

        
        public  Option<JumpData> GetJump(ulong id_0) {
            var __this_0 = this.nativePtr;
var id_1 = id_0;
            var __ret_0 = SpaceGame_get_jump(__this_0, id_1);
            var __ret_1 = RustOptionJumpData.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr SpaceGame_get_fleets(/* SpaceGame */ IntPtr __this);

        
        public  System.Collections.Generic.List<ObjData> GetFleets() {
            var __this_0 = this.nativePtr;

            var __ret_0 = SpaceGame_get_fleets(__this_0);
            var __ret_1 = RustVecObjData.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr SpaceGame_get_obj(/* SpaceGame */ IntPtr __this, ulong id);

        
        public  Option<ObjData> GetObj(ulong id_0) {
            var __this_0 = this.nativePtr;
var id_1 = id_0;
            var __ret_0 = SpaceGame_get_obj(__this_0, id_1);
            var __ret_1 = RustOptionObjData.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr SpaceGame_get_obj_coords(/* SpaceGame */ IntPtr __this, ulong id);

        
        public  Option<ObjCoords> GetObjCoords(ulong id_0) {
            var __this_0 = this.nativePtr;
var id_1 = id_0;
            var __ret_0 = SpaceGame_get_obj_coords(__this_0, id_1);
            var __ret_1 = RustOptionObjCoords.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void SpaceGame_update(/* SpaceGame */ IntPtr __this, float delta);

        
        public  void Update(float delta_0) {
            var __this_0 = this.nativePtr;
var delta_1 = delta_0;
            SpaceGame_update(__this_0, delta_1);
            
            
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr SpaceGame_take_events(/* SpaceGame */ IntPtr __this);

        
        public  System.Collections.Generic.List<EventData> TakeEvents() {
            var __this_0 = this.nativePtr;

            var __ret_0 = SpaceGame_take_events(__this_0);
            var __ret_1 = RustVecEventData.rust_to_dotnet(__ret_0);
            return __ret_1;
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr SpaceGame_list_wares(/* SpaceGame */ IntPtr __this);

        
        public  System.Collections.Generic.List<WareData> ListWares() {
            var __this_0 = this.nativePtr;

            var __ret_0 = SpaceGame_list_wares(__this_0);
            var __ret_1 = RustVecWareData.rust_to_dotnet(__ret_0);
            return __ret_1;
        }
} // class

    
    public class ObjFactory: IDisposable {
        internal IntPtr nativePtr;

        internal ObjFactory(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                ObjFactory_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void ObjFactory_delete(IntPtr __this);

        ~ObjFactory() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjFactory_is_producing(/* ObjFactory */ IntPtr __this);

        
        public  bool IsProducing() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjFactory_is_producing(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }
} // class

    
    public class ObjShipyard: IDisposable {
        internal IntPtr nativePtr;

        internal ObjShipyard(IntPtr nativePtr) {
            this.nativePtr = nativePtr;
        }

        public void Dispose() {
            DoDispose();
            GC.SuppressFinalize(this);
        }

        private void DoDispose() {
            if (nativePtr != IntPtr.Zero) {
                ObjShipyard_delete(nativePtr);
                nativePtr = IntPtr.Zero;
            }
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void ObjShipyard_delete(IntPtr __this);

        ~ObjShipyard() {
            DoDispose();
        }

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte ObjShipyard_is_producing(/* ObjShipyard */ IntPtr __this);

        
        public  bool IsProducing() {
            var __this_0 = this.nativePtr;

            var __ret_0 = ObjShipyard_is_producing(__this_0);
            var __ret_1 = (__ret_0 != 0);
            return __ret_1;
        }
} // class

    internal static class RustOptionTuple60float4432float62 {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionTuple60float4432float62_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionTuple60float4432float62_new_some(/* Option */ IntPtr value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr RustOptionTuple60float4432float62_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionTuple60float4432float62_is_some(IntPtr optPtr);

        internal static Option<Tuple<float, float>> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionTuple60float4432float62_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionTuple60float4432float62_take(optPtr);
                var value_1 = RustTuple2Tfloatfloat.rust_to_dotnet(value_0);
                return new Option<Tuple<float, float>>(value_1);
            }
            else
            {
                return new Option<Tuple<float, float>>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<Tuple<float, float>> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = RustTuple2Tfloatfloat.dotnet_to_rust(opt.Value);
                return RustOptionTuple60float4432float62_new_some(value_0);
            }
            else
            {
                return RustOptionTuple60float4432float62_new_none();
            }
        }
    }
    
    public static class RustVecEventData {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustVecEventData_new();
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecEventData_push(IntPtr vecPtr, /* EventData */ IntPtr element);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option<i_type> */ IntPtr RustVecEventData_iter_next(IntPtr iterPtr);
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecEventData_iter_delete(IntPtr iterPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* EventData */ IntPtr RustVecEventData_option_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustVecEventData_option_is_some(IntPtr optPtr);


        internal static System.Collections.Generic.List<EventData> rust_to_dotnet(IntPtr iterPtr) {
            var list = new System.Collections.Generic.List<EventData>();
            while (true)
            {
                var next_rust_opt = RustVecEventData.RustVecEventData_iter_next(iterPtr);
                if (RustVecEventData_option_is_some(next_rust_opt) == 0)
                {
                    break;
                }
                var value_rust = RustVecEventData_option_take(next_rust_opt);
                var value = new EventData(value_rust);
                list.Add(value);
            }
            RustVecEventData_iter_delete(iterPtr);
            return list;
        }

        internal static IntPtr dotnet_to_rust(System.Collections.Generic.List<EventData> list) {
            var vec = RustVecEventData_new();
            foreach (var element in list)
            {
                var i_element = element.nativePtr;
                RustVecEventData.RustVecEventData_push(vec, i_element);
            }
            return vec;
        }
    }
        
    internal static class RustOptionulong {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionulong_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionulong_new_some(ulong value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong RustOptionulong_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionulong_is_some(IntPtr optPtr);

        internal static Option<ulong> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionulong_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionulong_take(optPtr);
                var value_1 = value_0;
                return new Option<ulong>(value_1);
            }
            else
            {
                return new Option<ulong>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<ulong> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = opt.Value;
                return RustOptionulong_new_some(value_0);
            }
            else
            {
                return RustOptionulong_new_none();
            }
        }
    }
    
    internal static class RustOptionObjOrbitData {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjOrbitData_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjOrbitData_new_some(/* ObjOrbitData */ IntPtr value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* ObjOrbitData */ IntPtr RustOptionObjOrbitData_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionObjOrbitData_is_some(IntPtr optPtr);

        internal static Option<ObjOrbitData> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionObjOrbitData_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionObjOrbitData_take(optPtr);
                var value_1 = new ObjOrbitData(value_0);
                return new Option<ObjOrbitData>(value_1);
            }
            else
            {
                return new Option<ObjOrbitData>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<ObjOrbitData> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = opt.Value.nativePtr;
                return RustOptionObjOrbitData_new_some(value_0);
            }
            else
            {
                return RustOptionObjOrbitData_new_none();
            }
        }
    }
    
    internal static class RustTuple2Tfloatfloat {

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Tuple */ IntPtr RustTuple2Tfloatfloat_new(float t_1, float t_2);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern float RustTuple2Tfloatfloat_take_1(IntPtr tuple);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern float RustTuple2Tfloatfloat_take_2(IntPtr tuple);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustTuple2Tfloatfloat_delete(IntPtr tuple);

        internal static Tuple<float, float> rust_to_dotnet(IntPtr rustTuple)
        {
            var t_1_rust = RustTuple2Tfloatfloat_take_1(rustTuple);
            var t_1 = t_1_rust;
            var t_2_rust = RustTuple2Tfloatfloat_take_2(rustTuple);
            var t_2 = t_2_rust;
            var ret = Tuple.Create(t_1, t_2);
            RustTuple2Tfloatfloat_delete(rustTuple);
            return ret;
        }
        internal static /* Tuple */ IntPtr dotnet_to_rust(Tuple<float, float> tuple)
        {
            var t_1 = tuple.Item1;
            var t_1_rust = t_1;
            var t_2 = tuple.Item2;
            var t_2_rust = t_2;
            // We don't call delete in `Input` scenario. Rust-side conversion code will take care of it.
            return RustTuple2Tfloatfloat_new(t_1_rust, t_2_rust);            
        }
    }
    
    public static class RustVecJumpData {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustVecJumpData_new();
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecJumpData_push(IntPtr vecPtr, /* JumpData */ IntPtr element);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option<i_type> */ IntPtr RustVecJumpData_iter_next(IntPtr iterPtr);
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecJumpData_iter_delete(IntPtr iterPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* JumpData */ IntPtr RustVecJumpData_option_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustVecJumpData_option_is_some(IntPtr optPtr);


        internal static System.Collections.Generic.List<JumpData> rust_to_dotnet(IntPtr iterPtr) {
            var list = new System.Collections.Generic.List<JumpData>();
            while (true)
            {
                var next_rust_opt = RustVecJumpData.RustVecJumpData_iter_next(iterPtr);
                if (RustVecJumpData_option_is_some(next_rust_opt) == 0)
                {
                    break;
                }
                var value_rust = RustVecJumpData_option_take(next_rust_opt);
                var value = new JumpData(value_rust);
                list.Add(value);
            }
            RustVecJumpData_iter_delete(iterPtr);
            return list;
        }

        internal static IntPtr dotnet_to_rust(System.Collections.Generic.List<JumpData> list) {
            var vec = RustVecJumpData_new();
            foreach (var element in list)
            {
                var i_element = element.nativePtr;
                RustVecJumpData.RustVecJumpData_push(vec, i_element);
            }
            return vec;
        }
    }
        
    public static class RustVecObjData {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustVecObjData_new();
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecObjData_push(IntPtr vecPtr, /* ObjData */ IntPtr element);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option<i_type> */ IntPtr RustVecObjData_iter_next(IntPtr iterPtr);
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecObjData_iter_delete(IntPtr iterPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* ObjData */ IntPtr RustVecObjData_option_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustVecObjData_option_is_some(IntPtr optPtr);


        internal static System.Collections.Generic.List<ObjData> rust_to_dotnet(IntPtr iterPtr) {
            var list = new System.Collections.Generic.List<ObjData>();
            while (true)
            {
                var next_rust_opt = RustVecObjData.RustVecObjData_iter_next(iterPtr);
                if (RustVecObjData_option_is_some(next_rust_opt) == 0)
                {
                    break;
                }
                var value_rust = RustVecObjData_option_take(next_rust_opt);
                var value = new ObjData(value_rust);
                list.Add(value);
            }
            RustVecObjData_iter_delete(iterPtr);
            return list;
        }

        internal static IntPtr dotnet_to_rust(System.Collections.Generic.List<ObjData> list) {
            var vec = RustVecObjData_new();
            foreach (var element in list)
            {
                var i_element = element.nativePtr;
                RustVecObjData.RustVecObjData_push(vec, i_element);
            }
            return vec;
        }
    }
        
    internal static class RustOptionObjCoords {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjCoords_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjCoords_new_some(/* ObjCoords */ IntPtr value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* ObjCoords */ IntPtr RustOptionObjCoords_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionObjCoords_is_some(IntPtr optPtr);

        internal static Option<ObjCoords> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionObjCoords_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionObjCoords_take(optPtr);
                var value_1 = new ObjCoords(value_0);
                return new Option<ObjCoords>(value_1);
            }
            else
            {
                return new Option<ObjCoords>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<ObjCoords> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = opt.Value.nativePtr;
                return RustOptionObjCoords_new_some(value_0);
            }
            else
            {
                return RustOptionObjCoords_new_none();
            }
        }
    }
    
    internal static class RustTuple2Tulonguint {

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Tuple */ IntPtr RustTuple2Tulonguint_new(ulong t_1, uint t_2);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern ulong RustTuple2Tulonguint_take_1(IntPtr tuple);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern uint RustTuple2Tulonguint_take_2(IntPtr tuple);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustTuple2Tulonguint_delete(IntPtr tuple);

        internal static Tuple<ulong, uint> rust_to_dotnet(IntPtr rustTuple)
        {
            var t_1_rust = RustTuple2Tulonguint_take_1(rustTuple);
            var t_1 = t_1_rust;
            var t_2_rust = RustTuple2Tulonguint_take_2(rustTuple);
            var t_2 = t_2_rust;
            var ret = Tuple.Create(t_1, t_2);
            RustTuple2Tulonguint_delete(rustTuple);
            return ret;
        }
        internal static /* Tuple */ IntPtr dotnet_to_rust(Tuple<ulong, uint> tuple)
        {
            var t_1 = tuple.Item1;
            var t_1_rust = t_1;
            var t_2 = tuple.Item2;
            var t_2_rust = t_2;
            // We don't call delete in `Input` scenario. Rust-side conversion code will take care of it.
            return RustTuple2Tulonguint_new(t_1_rust, t_2_rust);            
        }
    }
    
    internal static class RustOptionObjCargo {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjCargo_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjCargo_new_some(/* ObjCargo */ IntPtr value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* ObjCargo */ IntPtr RustOptionObjCargo_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionObjCargo_is_some(IntPtr optPtr);

        internal static Option<ObjCargo> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionObjCargo_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionObjCargo_take(optPtr);
                var value_1 = new ObjCargo(value_0);
                return new Option<ObjCargo>(value_1);
            }
            else
            {
                return new Option<ObjCargo>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<ObjCargo> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = opt.Value.nativePtr;
                return RustOptionObjCargo_new_some(value_0);
            }
            else
            {
                return RustOptionObjCargo_new_none();
            }
        }
    }
    
    internal static class RustOptionObjFactory {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjFactory_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjFactory_new_some(/* ObjFactory */ IntPtr value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* ObjFactory */ IntPtr RustOptionObjFactory_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionObjFactory_is_some(IntPtr optPtr);

        internal static Option<ObjFactory> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionObjFactory_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionObjFactory_take(optPtr);
                var value_1 = new ObjFactory(value_0);
                return new Option<ObjFactory>(value_1);
            }
            else
            {
                return new Option<ObjFactory>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<ObjFactory> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = opt.Value.nativePtr;
                return RustOptionObjFactory_new_some(value_0);
            }
            else
            {
                return RustOptionObjFactory_new_none();
            }
        }
    }
    
    internal static class RustOptionObjAction {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjAction_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjAction_new_some(/* ObjAction */ IntPtr value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* ObjAction */ IntPtr RustOptionObjAction_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionObjAction_is_some(IntPtr optPtr);

        internal static Option<ObjAction> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionObjAction_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionObjAction_take(optPtr);
                var value_1 = new ObjAction(value_0);
                return new Option<ObjAction>(value_1);
            }
            else
            {
                return new Option<ObjAction>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<ObjAction> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = opt.Value.nativePtr;
                return RustOptionObjAction_new_some(value_0);
            }
            else
            {
                return RustOptionObjAction_new_none();
            }
        }
    }
    

        public class Option<T> {
        
            [System.Serializable]
            public class OptionNoneException : System.Exception
            {
                public OptionNoneException() :
                    base("Trying to get the value of an `Option` that is `None`") 
                {
                }
            }
        
            private T value;
            private bool isSome;
        
            public bool IsSome
            {
                get
                {
                    return isSome;
                }
            }
        
            public T Value
            {
                get {
                    if (!isSome) {
                        throw new OptionNoneException();
                    }
                    return value;
                }
            }
        
            public Option()
            {
                value = default(T);
                isSome = false;
            }
        
            public Option(T value)
            {
                if (value == null) 
                {
                    this.value = value;
                    this.isSome = false;
                }
                else
                {
                    this.value = value;
                    this.isSome = true;
                }
            }
        }        
        
    public static class RustVecSectorData {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustVecSectorData_new();
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecSectorData_push(IntPtr vecPtr, /* SectorData */ IntPtr element);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option<i_type> */ IntPtr RustVecSectorData_iter_next(IntPtr iterPtr);
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecSectorData_iter_delete(IntPtr iterPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* SectorData */ IntPtr RustVecSectorData_option_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustVecSectorData_option_is_some(IntPtr optPtr);


        internal static System.Collections.Generic.List<SectorData> rust_to_dotnet(IntPtr iterPtr) {
            var list = new System.Collections.Generic.List<SectorData>();
            while (true)
            {
                var next_rust_opt = RustVecSectorData.RustVecSectorData_iter_next(iterPtr);
                if (RustVecSectorData_option_is_some(next_rust_opt) == 0)
                {
                    break;
                }
                var value_rust = RustVecSectorData_option_take(next_rust_opt);
                var value = new SectorData(value_rust);
                list.Add(value);
            }
            RustVecSectorData_iter_delete(iterPtr);
            return list;
        }

        internal static IntPtr dotnet_to_rust(System.Collections.Generic.List<SectorData> list) {
            var vec = RustVecSectorData_new();
            foreach (var element in list)
            {
                var i_element = element.nativePtr;
                RustVecSectorData.RustVecSectorData_push(vec, i_element);
            }
            return vec;
        }
    }
        
    internal static class RustOptionJumpData {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionJumpData_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionJumpData_new_some(/* JumpData */ IntPtr value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* JumpData */ IntPtr RustOptionJumpData_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionJumpData_is_some(IntPtr optPtr);

        internal static Option<JumpData> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionJumpData_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionJumpData_take(optPtr);
                var value_1 = new JumpData(value_0);
                return new Option<JumpData>(value_1);
            }
            else
            {
                return new Option<JumpData>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<JumpData> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = opt.Value.nativePtr;
                return RustOptionJumpData_new_some(value_0);
            }
            else
            {
                return RustOptionJumpData_new_none();
            }
        }
    }
    
    public static class RustVecstring {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustVecstring_new();
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecstring_push(IntPtr vecPtr, /* RustString */ IntPtr element);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option<i_type> */ IntPtr RustVecstring_iter_next(IntPtr iterPtr);
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecstring_iter_delete(IntPtr iterPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* RustString */ IntPtr RustVecstring_option_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustVecstring_option_is_some(IntPtr optPtr);


        internal static System.Collections.Generic.List<string> rust_to_dotnet(IntPtr iterPtr) {
            var list = new System.Collections.Generic.List<string>();
            while (true)
            {
                var next_rust_opt = RustVecstring.RustVecstring_iter_next(iterPtr);
                if (RustVecstring_option_is_some(next_rust_opt) == 0)
                {
                    break;
                }
                var value_rust = RustVecstring_option_take(next_rust_opt);
                var value = RustString.rust_to_dotnet(value_rust);
                list.Add(value);
            }
            RustVecstring_iter_delete(iterPtr);
            return list;
        }

        internal static IntPtr dotnet_to_rust(System.Collections.Generic.List<string> list) {
            var vec = RustVecstring_new();
            foreach (var element in list)
            {
                var i_element = RustString.dotnet_to_rust(element);
                RustVecstring.RustVecstring_push(vec, i_element);
            }
            return vec;
        }
    }
        
    internal static class RustOptionObjData {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjData_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjData_new_some(/* ObjData */ IntPtr value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* ObjData */ IntPtr RustOptionObjData_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionObjData_is_some(IntPtr optPtr);

        internal static Option<ObjData> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionObjData_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionObjData_take(optPtr);
                var value_1 = new ObjData(value_0);
                return new Option<ObjData>(value_1);
            }
            else
            {
                return new Option<ObjData>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<ObjData> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = opt.Value.nativePtr;
                return RustOptionObjData_new_some(value_0);
            }
            else
            {
                return RustOptionObjData_new_none();
            }
        }
    }
    
    public static class RustVecWareData {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustVecWareData_new();
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecWareData_push(IntPtr vecPtr, /* WareData */ IntPtr element);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option<i_type> */ IntPtr RustVecWareData_iter_next(IntPtr iterPtr);
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecWareData_iter_delete(IntPtr iterPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* WareData */ IntPtr RustVecWareData_option_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustVecWareData_option_is_some(IntPtr optPtr);


        internal static System.Collections.Generic.List<WareData> rust_to_dotnet(IntPtr iterPtr) {
            var list = new System.Collections.Generic.List<WareData>();
            while (true)
            {
                var next_rust_opt = RustVecWareData.RustVecWareData_iter_next(iterPtr);
                if (RustVecWareData_option_is_some(next_rust_opt) == 0)
                {
                    break;
                }
                var value_rust = RustVecWareData_option_take(next_rust_opt);
                var value = new WareData(value_rust);
                list.Add(value);
            }
            RustVecWareData_iter_delete(iterPtr);
            return list;
        }

        internal static IntPtr dotnet_to_rust(System.Collections.Generic.List<WareData> list) {
            var vec = RustVecWareData_new();
            foreach (var element in list)
            {
                var i_element = element.nativePtr;
                RustVecWareData.RustVecWareData_push(vec, i_element);
            }
            return vec;
        }
    }
        
    public static class RustVecTuple60ulong4432uint62 {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustVecTuple60ulong4432uint62_new();
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecTuple60ulong4432uint62_push(IntPtr vecPtr, /* Option */ IntPtr element);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option<i_type> */ IntPtr RustVecTuple60ulong4432uint62_iter_next(IntPtr iterPtr);
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void RustVecTuple60ulong4432uint62_iter_delete(IntPtr iterPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* Option */ IntPtr RustVecTuple60ulong4432uint62_option_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustVecTuple60ulong4432uint62_option_is_some(IntPtr optPtr);


        internal static System.Collections.Generic.List<Tuple<ulong, uint>> rust_to_dotnet(IntPtr iterPtr) {
            var list = new System.Collections.Generic.List<Tuple<ulong, uint>>();
            while (true)
            {
                var next_rust_opt = RustVecTuple60ulong4432uint62.RustVecTuple60ulong4432uint62_iter_next(iterPtr);
                if (RustVecTuple60ulong4432uint62_option_is_some(next_rust_opt) == 0)
                {
                    break;
                }
                var value_rust = RustVecTuple60ulong4432uint62_option_take(next_rust_opt);
                var value = RustTuple2Tulonguint.rust_to_dotnet(value_rust);
                list.Add(value);
            }
            RustVecTuple60ulong4432uint62_iter_delete(iterPtr);
            return list;
        }

        internal static IntPtr dotnet_to_rust(System.Collections.Generic.List<Tuple<ulong, uint>> list) {
            var vec = RustVecTuple60ulong4432uint62_new();
            foreach (var element in list)
            {
                var i_element = RustTuple2Tulonguint.dotnet_to_rust(element);
                RustVecTuple60ulong4432uint62.RustVecTuple60ulong4432uint62_push(vec, i_element);
            }
            return vec;
        }
    }
        
    internal static class RustOptionObjShipyard {
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjShipyard_new_none();

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RustOptionObjShipyard_new_some(/* ObjShipyard */ IntPtr value);
        
        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern /* ObjShipyard */ IntPtr RustOptionObjShipyard_take(IntPtr optPtr);

        [DllImport("ffi_domain_2_native", CallingConvention = CallingConvention.Cdecl)]
        internal static extern byte RustOptionObjShipyard_is_some(IntPtr optPtr);

        internal static Option<ObjShipyard> rust_to_dotnet(IntPtr optPtr)
        {
            if (RustOptionObjShipyard_is_some(optPtr) != 0)
            {
                var value_0 = RustOptionObjShipyard_take(optPtr);
                var value_1 = new ObjShipyard(value_0);
                return new Option<ObjShipyard>(value_1);
            }
            else
            {
                return new Option<ObjShipyard>();
            }
        }

        internal static IntPtr dotnet_to_rust(Option<ObjShipyard> opt)
        {
            if (opt.IsSome)
            {
                var value_0 = opt.Value.nativePtr;
                return RustOptionObjShipyard_new_some(value_0);
            }
            else
            {
                return RustOptionObjShipyard_new_none();
            }
        }
    }
    } // namespace
